image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
- build
- publish

variables:
  Configuration: Release
  
build:
  stage: build
  script:
  - dotnet build -c Release
  - dotnet test tests/UnitTests/UnitTests.csproj
  artifacts:
    paths:
      - "src/**/*.nupkg"
