version: 5.2.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release
test_script:
- ps: dotnet test tests/UnitTests/UnitTests.csproj
artifacts:
- path: src\**\*.nupkg