name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      Configuration: Release
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - if: ${{ env.PUSH_PACKAGES }} == 'true'
      name: Publish NuGet
      run: dotnet nuget push --skip-duplicate **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
